name: Java CI

on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: make build

      - name: Test & Code coverage
        uses: qltysh/qlty-action/coverage@main
        run: make report
        env:
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
          coverage-token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: /app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco